apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saas-investigator.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "saas-investigator.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "saas-investigator.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          env:
            - name: PORT
              value: "{{ .Values.backend.service.port }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          command: ["node", "server.js"]
