apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saas-investigator.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "saas-investigator.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "saas-investigator.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          env:
            - name: PORT
              value: "{{ .Values.frontend.service.port }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          command: ["npm", "start"]
